### PR TITLE
switch mapping to openMINDS Python classes

### PR DESCRIPTION
**Pull request by lzehl**
Started to solve / tackle #7 

Suggestion:
1. Switch mapping dict to openMINDS instance names.
2. Make use of instance functionality of openMINDS Python: `TYPE.by_name("INSTANCENAME")`
For2. Maybe introduce utility function to make instance reference and adding instance to collection (optional) at the same time.

@apdavison @Peyman-N please let me know if you agree with this approach before I continue with this PR.

### CODE REVIEW

**Review by apdavison — COMMENTED** [review]
Looks good to me.

**Comment by lzehl** [comment]
note to me: https://radiopaedia.org/articles/mri-pulse-sequences-1

**Comment by lzehl** [comment]
@Peyman-N I reduced to what we currently know. Some PRs in instances are still missing for making the mapping run.

**Comment by lzehl** [comment]
@Peyman-N please replace the respective code in the conversion for the mapping (using openMINDS python extract instance by name function)

Note for Technique you need to try / loop over these types AnalysisTechnique, StimulationApproach, StimulationTechnique or Technique

**Comment by lzehl** [comment]
@Peyman-N I forgot MRIPulseSequence in the list of technique types to loop over

**Pull request merged**
